name: Reset master branch to main
on:
  push:
    branches:
      - main
jobs:
  reset:
    name: Runner
    runs-on: ubuntu-latest
    steps:
      - name: Reset master branch to main
        uses: nicksnell/action-reset-repo@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          base_branch: main
          reset_branch: master
